### ISSUE TITLE
Should we remove chats so tests fail or ensure they have N chats?

### ISSUE THREAD

**Issue by rrhyne** [saadfrhan/react-todoapp#3]
We want users who take the test to add their chat log to the repository. We have this written in the test instructions, but I thought adding a test would ensure that step is complete as a condition of correctness. 

We could remove the chats file all together, or start with an empty chat file and test the JSON structure for at least one chat log. 

Or perhaps we should not abuse unit tests at all to accomplish this and rely on the test instructions. 

What do you think?

**Comment by ghost** [comment]
Tell me a specific thing to do about that. I agreed on the problem.

**Comment by ghost** [comment]
If we clear the chats.json file, one more template would be needed for No AI tasks (because that test case will fail in No AI), and in that, there would be no chats.json and the test case that checks for it.

**Comment by rrhyne** [comment]
I think you should choose the path that works best!

**Comment by ghost** [comment]
Ok!

**Comment by ghost** [comment]
I have created two templates and moved them to https://github.com/SGCodyResearch. 
Hello @meglynst, I am updating the template field in the classrooms.
